---
title: "EMD Clustering"
author: "Andrea Stancescu and Lucy Liu"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Below are the packages that we will be using:

```{r}
library(Barycenter)
library(Rcpp)
library(HistDAWass)
```

Here is a sample of visualizing 5 different handwritten images of the number "8"
```{r}
image(eight[[1]])
image(eight[[2]])
image(eight[[3]])
image(eight[[4]])
image(eight[[5]])
```

Now we will compute the barycenter of these images and visualize the barycenter
using Barycenter::WaBarycenter() function
```{r}
barycenter <- WaBarycenter(eight)
image(barycenter)
```


Below is the EMD clustering algorithm using Wasserstein distances on the MNIST training data set:
```{r}
to.read = file("C:\\Users\\Andrea\\Downloads\\train-images.idx3-ubyte", 'rb')

# create lists of histogram distributions
img_mnist = vector("list",25)
for (i in 1:25) {
  m = matrix(readBin(to.read,integer(), size=1, n=28*28, endian="big"),28,28)
  img_mnist[[i]] = data2hist(m, type = "regular")
  image(m[,28:1])
}

to.read = file("C:\\Users\\Andrea\\Downloads\\train-images.idx3-ubyte", 'rb')
readBin(to.read, integer(), n=4, endian="big")
par(mfrow=c(5,5))
par(mar=c(0,0,0,0))
for(i in 1:25){m = matrix(readBin(to.read,integer(), size=1, n=28*28, endian="big"),28,28);image(m[,28:1])}

# combine separate lists into a matrix of histogram objects
mymat = new("MatH", nrows=25, ncols=1, ListOfDist=img_mnist, names.rows=c(1:25), names.cols="density")
WH_adaptive.kmeans(mymat, k=3)
```









